Scripts
Jartreg/prometeus-https-demo pull request #2
Opened 2018-06-11 16:30 UTC by Travior

2018-06-11 17:19 UTC, Jartreg reviewed
Das ist ja eigentlich erstmal nur für die Präsentation gedacht... Wär's nicht besser, du machst das so, dass du das für die Beispiele nur auszuführen brauchst?

2018-06-11 17:19 UTC, Jartreg commented on ipforward.py
> +    print("                                                                   |___/ ")
Ist das wirklich nötig?

2018-06-11 17:21 UTC, Jartreg requested changes
Am Besten wär's vielleicht noch, wenn du das in einen Unterordner tun würdest.

2018-06-11 20:21 UTC, Travior commented on ipforward.py
> +    print("                                                                   |___/ ")
Ja wirklich alle scripts nehmen so etwas als überschrift. Ist eine alte kali manier ;)

2018-06-11 20:32 UTC, Travior reviewed
Now featuring multiple pages
Extended Menu, to undo changes

2018-06-11 20:38 UTC, Travior commented
> Das ist ja eigentlich erstmal nur für die Präsentation gedacht... Wär's nicht besser, du machst das so, dass du das für die Beispiele nur auszuführen brauchst?

Das ist es ja erstmal, macht ja keinen großen unterschied ob ich jetzt noch 2 Tasten drücke oder nicht. Ist halt nur vielleicht für das Verständnis einfacher

2018-06-14 18:58 UTC, Jartreg requested changes
Hier noch ein paar Verbesserungsvorschläge was die Schönheit angeht. Zudem sollte das das gesamte Projekt bis auf den Code auf deutsch sein. Daher wäre es gut, wenn du die englischen Ausgaben ("Wrong parameter" usw...) durch deutsche ersetzen könntest...

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +endlessrun = True
Die Variable wird doch eigentlich nicht gebraucht, oder? Warum nicht
```python
while True:
```

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +switchPage = False
Die Variable ist unnötig

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +option6 = False
Diese Namen sind doch nicht dein Ernst, oder?

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option1 = True
Kannst du [Zeile 38](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R38) nicht schon hierhin tun? Dann sind diese ganzen optionN-Variablen nicht mehr nötig...

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option2 = True
Das gleiche hier mit [Zeile 41](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R41)

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option3 = True
Das gleiche hier mit [Zeile 44](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R44)

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option4 = True
Siehe [Zeile 81](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R81)

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option5 = True
Siehe [Zeile 84](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R84)

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +            option6 = True
Siehe [Zeile 87](https://github.com/Jartreg/prometeus-https-demo/pull/2/files#diff-3d8b37ff3bf410808455cc34849671c9R87)

2018-06-14 18:58 UTC, Jartreg commented on ipforward.py
> +        print("                                                                   |___/ ")
Du wiederholst hier das gesamte Banner... Tu das doch in 'ne Funktion

2018-06-15 16:41 UTC, Jartreg commented on scripts/arpspoof/arpspoof_main.py
> +        pass
Unnötiger `else`-Zweig

2018-06-15 16:41 UTC, Jartreg submitted a review, later dismissed

2018-07-06 18:27 UTC, Jartreg approved these changes

2018-07-06 18:28 UTC, merged